language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo-dev/maintainer-quality-tools.git -b master-add-custom-check-moylop260 ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
# example: dependency
# - git clone https://github.com/OCA/webkit-tools -b ${VERSION} $HOME/webkit-tools

script:
  - travis_run_tests

after_success:
  coveralls
